apiVersion: skaffold/v2beta26
kind: Config

build:
  artifacts:
    - image: docker.io/rustycain/k8-gockey
    - image: docker.io/rustycain/k8-gockey-data-migration
      docker:
        dockerfile: ./Dockerfile
  local:
    push: false
    concurrency: 1

deploy:
  helm:
    flags:
      upgrade: ["--timeout", "15m"]
      install: ["--timeout", "15m"]
    releases:
    - name: test
      chartPath: k8-gockey
      wait: true
      artifactOverrides:
        skaffoldImage: docker.io/rustycain/k8-gockey
        migration.skaffoldImage: docker.io/rustycain/k8-gockey-data-migration
      setValueTemplates:
        skaffold: true
        image.pullPolicy: Never
        migration.image.pullPolicy: Never

profiles:
  - name: mysql
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValueTemplates/mysql.enabled
        value: true

portForward:
- resourceType: deployment
  resourceName: test-k8-gockey
  namespace: default
  port: 8080
  localPort: 8080