INSERT INTO leagues (id, name) VALUES
    (1, 'Metro'),
    (2, 'Atlantic'),
    (3, 'Central'),
    (4, 'Pacific');


INSERT INTO teams (name, league_id) VALUES
    ('Anaheim Bruins', 4),
    ('Boston Sabres', 1),
    ('Buffalo Flames', 1),
    ('Calgary Hurricanes', 2),
    ('Carolina Blackhawks', 2),
    ('Chicago Avalanche', 3),
    ('Colorado Blue Jackets', 3),
    ('Columbus Stars', 3),
    ('Dallas Red Wings', 4),
    ('Detroit Oilers', 2),
    ('Edmonton Panthers', 4),
    ('Florida Angeles Kings', 2),
    ('Los Angeles Wild', 4),
    ('Minnesota Canadiens', 3),
    ('Montreal Predators', 1),
    ('Nashville Jersey Devils', 3),
    ('New York Islanders', 2),
    ('New York Rangers', 2),
    ('New York Senators', 2),
    ('Ottawa Senators Flyers', 1),
    ('Philadelphia Penguins', 2),
    ('Pittsburgh Jose Sharks', 2),
    ('San Jose Kraken', 4),
    ('Seattle Louis Blues', 3),
    ('St Louis Bay Lightning', 3),
    ('Tampa Bay Maple Leafs', 1),
    ('Toronto Hockey Club', 1),
    ('Utah Hockey Canucks', 4),
    ('Vancouver Golden Knights', 4),
    ('Vegas Golden Capitals', 4),
    ('Washington Jets', 2),
    ('Winnipeg Ducks', 4);
