name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image on Github
      run: docker build . --file Dockerfile --tag rustycain/gockey-server:$(date +%s) && docker push rustycain/gockey-server:$(date +%s)
